import { storage } from '../cool';
import dev from './dev';
import prod from './prod';

// 是否开发模式
export const isDev = import.meta.env.DEV;

// 配置
export const config = {
	// 项目信息
	app: {
		name: import.meta.env.VITE_NAME,

		// 菜单
		menu: {
			// 是否分组显示
			isGroup: false,
			// 自定义菜单列表
			list: [
				{
					"id": 56,
					"createTime": "2025-02-19 10:56:27",
					"updateTime": "2025-02-19 10:56:27",
					"tenantId": null,
					"parentId": 54,
					"name": "单个信息",
					"router": null,
					"perms": "recycle:data:info",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 27,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 26,
					"name": "新增",
					"router": null,
					"perms": "base:sys:param:add",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 28,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 26,
					"name": "修改",
					"router": null,
					"perms": "base:sys:param:info,base:sys:param:update",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 29,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 26,
					"name": "删除",
					"router": null,
					"perms": "base:sys:param:delete",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 30,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 26,
					"name": "查看",
					"router": null,
					"perms": "base:sys:param:page,base:sys:param:list,base:sys:param:info",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 64,
					"createTime": "2025-02-19 10:56:27",
					"updateTime": "2025-02-19 10:56:27",
					"tenantId": null,
					"parentId": 61,
					"name": "单个信息",
					"router": null,
					"perms": "user:info:info",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 63,
					"createTime": "2025-02-19 10:56:27",
					"updateTime": "2025-02-19 10:56:27",
					"tenantId": null,
					"parentId": 61,
					"name": "修改",
					"router": null,
					"perms": "user:info:update,user:info:info",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 62,
					"createTime": "2025-02-19 10:56:27",
					"updateTime": "2025-02-19 10:56:27",
					"tenantId": null,
					"parentId": 61,
					"name": "删除",
					"router": null,
					"perms": "user:info:delete",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 35,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 34,
					"name": "任务列表",
					"router": "/task/list",
					"perms": null,
					"type": 1,
					"icon": "icon-menu",
					"orderNum": 0,
					"viewPath": "modules/task/views/list.vue",
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 36,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 35,
					"name": "权限",
					"router": null,
					"perms": "task:info:page,task:info:list,task:info:info,task:info:add,task:info:delete,task:info:update,task:info:stop,task:info:start,task:info:once,task:info:log",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 59,
					"createTime": "2025-02-19 10:56:27",
					"updateTime": "2025-02-19 10:56:27",
					"tenantId": null,
					"parentId": 58,
					"name": "权限",
					"router": null,
					"perms": "space:type:delete,space:type:update,space:type:info,space:type:list,space:type:page,space:type:add,space:info:getConfig,space:info:delete,space:info:update,space:info:info,space:info:list,space:info:page,space:info:add",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 38,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 37,
					"name": "文档官网",
					"router": "/tutorial/doc",
					"perms": null,
					"type": 1,
					"icon": "icon-log",
					"orderNum": 0,
					"viewPath": "https://admin.cool-js.com",
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 57,
					"createTime": "2025-02-19 10:56:27",
					"updateTime": "2025-02-19 10:56:27",
					"tenantId": null,
					"parentId": 54,
					"name": "分页查询",
					"router": null,
					"perms": "recycle:data:page",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 26,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 25,
					"name": "参数列表",
					"router": "/sys/param",
					"perms": null,
					"type": 1,
					"icon": "icon-menu",
					"orderNum": 0,
					"viewPath": "cool/modules/base/views/param.vue",
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 55,
					"createTime": "2025-02-19 10:56:27",
					"updateTime": "2025-02-19 10:56:27",
					"tenantId": null,
					"parentId": 54,
					"name": "恢复数据",
					"router": null,
					"perms": "recycle:data:restore",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 42,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 11:14:48",
					"tenantId": null,
					"parentId": null,
					"name": "首页",
					"router": "/",
					"perms": null,
					"type": 1,
					"icon": null,
					"orderNum": 0,
					"viewPath": "modules/demo/views/home/index.vue",
					"keepAlive": true,
					"isShow": false
				},
				{
					"id": 53,
					"createTime": "2025-02-19 10:56:27",
					"updateTime": "2025-02-19 10:56:27",
					"tenantId": null,
					"parentId": 44,
					"name": "字典类型",
					"router": null,
					"perms": "dict:type:delete,dict:type:update,dict:type:info,dict:type:list,dict:type:page,dict:type:add",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 52,
					"createTime": "2025-02-19 10:56:27",
					"updateTime": "2025-02-19 10:56:27",
					"tenantId": null,
					"parentId": 44,
					"name": "组权限",
					"router": null,
					"perms": "dict:type:list,dict:type:update,dict:type:delete,dict:type:add",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 45,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 44,
					"name": "删除",
					"router": null,
					"perms": "dict:info:delete",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 46,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 44,
					"name": "修改",
					"router": null,
					"perms": "dict:info:update,dict:info:info",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 47,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 44,
					"name": "获得字典数据",
					"router": null,
					"perms": "dict:info:data",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 48,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 44,
					"name": "单个信息",
					"router": null,
					"perms": "dict:info:info",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 49,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 44,
					"name": "列表查询",
					"router": null,
					"perms": "dict:info:list",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 50,
					"createTime": "2025-02-19 10:56:27",
					"updateTime": "2025-02-19 10:56:27",
					"tenantId": null,
					"parentId": 44,
					"name": "分页查询",
					"router": null,
					"perms": "dict:info:page",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 51,
					"createTime": "2025-02-19 10:56:27",
					"updateTime": "2025-02-19 10:56:27",
					"tenantId": null,
					"parentId": 44,
					"name": "新增",
					"router": null,
					"perms": "dict:info:add",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 14,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 2,
					"name": "用户列表",
					"router": "/sys/user",
					"perms": null,
					"type": 1,
					"icon": "icon-user",
					"orderNum": 0,
					"viewPath": "modules/base/views/user/index.vue",
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 76,
					"createTime": "2025-02-19 10:56:27",
					"updateTime": "2025-02-19 10:56:27",
					"tenantId": null,
					"parentId": 69,
					"name": "新增",
					"router": null,
					"perms": "plugin:info:add",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 75,
					"createTime": "2025-02-19 10:56:27",
					"updateTime": "2025-02-19 10:56:27",
					"tenantId": null,
					"parentId": 69,
					"name": "列表查询",
					"router": null,
					"perms": "plugin:info:list",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 74,
					"createTime": "2025-02-19 10:56:27",
					"updateTime": "2025-02-19 10:56:27",
					"tenantId": null,
					"parentId": 69,
					"name": "修改",
					"router": null,
					"perms": "plugin:info:update",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 73,
					"createTime": "2025-02-19 10:56:27",
					"updateTime": "2025-02-19 10:56:27",
					"tenantId": null,
					"parentId": 69,
					"name": "安装插件",
					"router": null,
					"perms": "plugin:info:install",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 72,
					"createTime": "2025-02-19 10:56:27",
					"updateTime": "2025-02-19 10:56:27",
					"tenantId": null,
					"parentId": 69,
					"name": "单个信息",
					"router": null,
					"perms": "plugin:info:info",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 7,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 3,
					"name": "参数",
					"router": "/test/aa",
					"perms": null,
					"type": 1,
					"icon": "icon-goods",
					"orderNum": 0,
					"viewPath": "modules/base/views/info.vue",
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 8,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 3,
					"name": "编辑",
					"router": null,
					"perms": "base:sys:menu:info,base:sys:menu:update",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 71,
					"createTime": "2025-02-19 10:56:27",
					"updateTime": "2025-02-19 10:56:27",
					"tenantId": null,
					"parentId": 69,
					"name": "分页查询",
					"router": null,
					"perms": "plugin:info:page",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 70,
					"createTime": "2025-02-19 10:56:27",
					"updateTime": "2025-02-19 10:56:27",
					"tenantId": null,
					"parentId": 69,
					"name": "删除",
					"router": null,
					"perms": "plugin:info:delete",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 67,
					"createTime": "2025-02-19 10:56:27",
					"updateTime": "2025-02-19 10:56:27",
					"tenantId": null,
					"parentId": 61,
					"name": "新增",
					"router": null,
					"perms": "user:info:add",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 66,
					"createTime": "2025-02-19 10:56:27",
					"updateTime": "2025-02-19 10:56:27",
					"tenantId": null,
					"parentId": 61,
					"name": "分页查询",
					"router": null,
					"perms": "user:info:page",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 15,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 14,
					"name": "部门列表",
					"router": null,
					"perms": "base:sys:department:list",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 16,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 14,
					"name": "新增部门",
					"router": null,
					"perms": "base:sys:department:add",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 17,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 14,
					"name": "更新部门",
					"router": null,
					"perms": "base:sys:department:update",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 18,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 14,
					"name": "删除部门",
					"router": null,
					"perms": "base:sys:department:delete",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 19,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 14,
					"name": "部门排序",
					"router": null,
					"perms": "base:sys:department:order",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 20,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 14,
					"name": "用户转移",
					"router": null,
					"perms": "base:sys:user:move",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 21,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 14,
					"name": "新增",
					"router": null,
					"perms": "base:sys:user:add",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 22,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 14,
					"name": "删除",
					"router": null,
					"perms": "base:sys:user:delete",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 23,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 14,
					"name": "修改",
					"router": null,
					"perms": "base:sys:user:delete,base:sys:user:update",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 24,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 14,
					"name": "查询",
					"router": null,
					"perms": "base:sys:user:page,base:sys:user:list,base:sys:user:info",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 65,
					"createTime": "2025-02-19 10:56:27",
					"updateTime": "2025-02-19 10:56:27",
					"tenantId": null,
					"parentId": 61,
					"name": "列表查询",
					"router": null,
					"perms": "user:info:list",
					"type": 2,
					"icon": null,
					"orderNum": 0,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 39,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 37,
					"name": "crud 示例",
					"router": "/demo/crud",
					"perms": null,
					"type": 1,
					"icon": "icon-favor",
					"orderNum": 1,
					"viewPath": "modules/demo/views/crud/index.vue",
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 69,
					"createTime": "2025-02-19 10:56:27",
					"updateTime": "2025-02-19 10:56:27",
					"tenantId": null,
					"parentId": 68,
					"name": "插件列表",
					"router": "/helper/plugins",
					"perms": null,
					"type": 1,
					"icon": "icon-list",
					"orderNum": 1,
					"viewPath": "modules/helper/views/plugins.vue",
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 61,
					"createTime": "2025-02-19 10:56:27",
					"updateTime": "2025-02-19 10:56:27",
					"tenantId": null,
					"parentId": 60,
					"name": "用户列表",
					"router": "/user/list",
					"perms": null,
					"type": 1,
					"icon": "icon-menu",
					"orderNum": 1,
					"viewPath": "modules/user/views/list.vue",
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 10,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 9,
					"name": "新增",
					"router": null,
					"perms": "base:sys:role:add",
					"type": 2,
					"icon": null,
					"orderNum": 1,
					"viewPath": null,
					"keepAlive": false,
					"isShow": true
				},
				{
					"id": 41,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 40,
					"name": "图片上传",
					"router": null,
					"perms": "space:info:page,space:info:list,space:info:info,space:info:add,space:info:delete,space:info:update,space:type:page,space:type:list,space:type:info,space:type:add,space:type:delete,space:type:update",
					"type": 2,
					"icon": null,
					"orderNum": 1,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 2,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 1,
					"name": "权限管理",
					"router": null,
					"perms": null,
					"type": 0,
					"icon": "icon-auth",
					"orderNum": 1,
					"viewPath": null,
					"keepAlive": false,
					"isShow": true
				},
				{
					"id": 32,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 31,
					"name": "请求日志",
					"router": "/sys/log",
					"perms": null,
					"type": 1,
					"icon": "icon-log",
					"orderNum": 1,
					"viewPath": "cool/modules/base/views/log.vue",
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 33,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 32,
					"name": "权限",
					"router": null,
					"perms": "base:sys:log:page,base:sys:log:clear,base:sys:log:getKeep,base:sys:log:setKeep",
					"type": 2,
					"icon": null,
					"orderNum": 1,
					"viewPath": null,
					"keepAlive": false,
					"isShow": true
				},
				{
					"id": 4,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 3,
					"name": "新增",
					"router": null,
					"perms": "base:sys:menu:add",
					"type": 2,
					"icon": null,
					"orderNum": 1,
					"viewPath": null,
					"keepAlive": false,
					"isShow": true
				},
				{
					"id": 5,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 3,
					"name": "删除",
					"router": null,
					"perms": "base:sys:menu:delete",
					"type": 2,
					"icon": null,
					"orderNum": 2,
					"viewPath": null,
					"keepAlive": false,
					"isShow": true
				},
				{
					"id": 11,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 9,
					"name": "删除",
					"router": null,
					"perms": "base:sys:role:delete",
					"type": 2,
					"icon": null,
					"orderNum": 2,
					"viewPath": null,
					"keepAlive": false,
					"isShow": true
				},
				{
					"id": 3,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 2,
					"name": "菜单列表",
					"router": "/sys/menu",
					"perms": null,
					"type": 1,
					"icon": "icon-menu",
					"orderNum": 2,
					"viewPath": "modules/base/views/menu/index.vue",
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 1,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": null,
					"name": "系统管理",
					"router": "/sys",
					"perms": null,
					"type": 0,
					"icon": "icon-set",
					"orderNum": 2,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 25,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 1,
					"name": "参数配置",
					"router": null,
					"perms": null,
					"type": 0,
					"icon": "icon-params",
					"orderNum": 3,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 12,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 9,
					"name": "修改",
					"router": null,
					"perms": "base:sys:role:update",
					"type": 2,
					"icon": null,
					"orderNum": 3,
					"viewPath": null,
					"keepAlive": false,
					"isShow": true
				},
				{
					"id": 9,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 2,
					"name": "角色列表",
					"router": "/sys/role",
					"perms": null,
					"type": 1,
					"icon": "icon-dept",
					"orderNum": 3,
					"viewPath": "cool/modules/base/views/role.vue",
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 44,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 43,
					"name": "字典管理",
					"router": "/dict/list",
					"perms": null,
					"type": 1,
					"icon": "icon-dict",
					"orderNum": 3,
					"viewPath": "modules/dict/views/list.vue",
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 6,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 3,
					"name": "查询",
					"router": null,
					"perms": "base:sys:menu:page,base:sys:menu:list,base:sys:menu:info",
					"type": 2,
					"icon": null,
					"orderNum": 4,
					"viewPath": null,
					"keepAlive": false,
					"isShow": true
				},
				{
					"id": 13,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 9,
					"name": "查询",
					"router": null,
					"perms": "base:sys:role:page,base:sys:role:list,base:sys:role:info",
					"type": 2,
					"icon": null,
					"orderNum": 4,
					"viewPath": null,
					"keepAlive": false,
					"isShow": true
				},
				{
					"id": 58,
					"createTime": "2025-02-19 10:56:27",
					"updateTime": "2025-02-19 10:56:27",
					"tenantId": null,
					"parentId": 43,
					"name": "文件管理",
					"router": "/upload/list",
					"perms": null,
					"type": 1,
					"icon": "icon-log",
					"orderNum": 5,
					"viewPath": "modules/space/views/list.vue",
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 54,
					"createTime": "2025-02-19 10:56:27",
					"updateTime": "2025-02-19 10:56:27",
					"tenantId": null,
					"parentId": 43,
					"name": "数据回收站",
					"router": "/recycle/data",
					"perms": null,
					"type": 1,
					"icon": "icon-delete",
					"orderNum": 6,
					"viewPath": "modules/recycle/views/data.vue",
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 43,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": null,
					"name": "数据管理",
					"router": null,
					"perms": null,
					"type": 0,
					"icon": "icon-data",
					"orderNum": 7,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 68,
					"createTime": "2025-02-19 10:56:27",
					"updateTime": "2025-02-19 10:56:27",
					"tenantId": null,
					"parentId": null,
					"name": "扩展管理",
					"router": null,
					"perms": null,
					"type": 0,
					"icon": "icon-favor",
					"orderNum": 8,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 31,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 1,
					"name": "监控管理",
					"router": null,
					"perms": null,
					"type": 0,
					"icon": "icon-monitor",
					"orderNum": 9,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 34,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": 1,
					"name": "任务管理",
					"router": null,
					"perms": null,
					"type": 0,
					"icon": "icon-activity",
					"orderNum": 9,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 60,
					"createTime": "2025-02-19 10:56:27",
					"updateTime": "2025-02-19 10:56:27",
					"tenantId": null,
					"parentId": null,
					"name": "用户管理",
					"router": null,
					"perms": null,
					"type": 0,
					"icon": "icon-user",
					"orderNum": 11,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 37,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": null,
					"name": "框架教程",
					"router": "/tutorial",
					"perms": null,
					"type": 0,
					"icon": "icon-task",
					"orderNum": 98,
					"viewPath": null,
					"keepAlive": true,
					"isShow": true
				},
				{
					"id": 40,
					"createTime": "2025-02-19 10:56:26",
					"updateTime": "2025-02-19 10:56:26",
					"tenantId": null,
					"parentId": null,
					"name": "通用",
					"router": null,
					"perms": null,
					"type": 0,
					"icon": "icon-radioboxfill",
					"orderNum": 99,
					"viewPath": null,
					"keepAlive": true,
					"isShow": false
				}
			]
		},

		// 路由
		router: {
			// 模式
			mode: import.meta.env.MODE == 'static' ? 'hash' : 'history',
			// 转场动画
			transition: 'slide'
		}
	},

	// 国际化配置
	i18n: {
		locale: storage.get('locale') || 'zh-cn',
		languages: [
			{
				label: '中文',
				value: 'zh-cn'
			},
			{
				label: '繁体中文',
				value: 'zh-tw'
			},
			{
				label: 'English',
				value: 'en'
			}
		]
	},

	// 忽略规则
	ignore: {
		// 不显示请求进度条
		NProgress: ['__cool_*'],
		// 页面不需要登录验证
		token: []
	},

	// 当前环境
	...(isDev ? dev : prod)
};

export * from './proxy';
